version: '3.9'

services:

  java_app:
    container_name: java_app
    image: java_app:1.0.0
    build: .
    ports:
      - 8080
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/stepup
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - web

  web:
    container_name: web
    image: tomcat:9.0
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    container_name: pg_stepup
    image: postgres:latest
    environment:
      POSTGRES_DB: stepup
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../pg_script:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  pgdata: {}

