version: '3.9'

services:
  postgres:
    container_name: pg_stepup
    image: postgres:latest
    environment:
      POSTGRES_DB: stepup
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pg_script:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
